<a href="https://colab.research.google.com/github/srika16/NLP_with_Transformers/blob/main/Neural_Networks_From_Scratch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

input = [1, 2 ,3, 2.5]
weights = [0.2, 0.8, -0.5, 1.0]
bias = 2

output = (input[0] * weights[0] +
          input[1] * weights[1] +
          input[2] * weights[2] +
          input[3] * weights[3] + bias)

print(output)


inputs = [1, 2, 3, 2.5]

weights1 = [0.2, 0.8, -0.5, 1]
weights2 = [0.5, -0.91, 0.26 ,-0.5]
weights3 = [-0.26, -0.27, 0.17, 0.87]

bias1 = 2
bias2 = 3
bias3 = 0.5

outputs = [
    # Neuron 1
    inputs[0] * weights1[0] +
    inputs[1] * weights1[1] +
    inputs[2] * weights1[2] +
    inputs[3] * weights1[3] + bias1,

    # Neuron 2
    inputs[0] * weights2[0] +
    inputs[1] * weights2[1] +
    inputs[2] * weights2[2] +
    inputs[3] * weights2[3] + bias2,

    # Neuron 3
    inputs[0] * weights3[0] +
    inputs[1] * weights3[1] +
    inputs[2] * weights3[2] +
    inputs[3] * weights3[3] + bias3

]

print(outputs)

inputs = [1, 2, 3, 2.5]

weights = [[0.2, 0.8, -0.5, 1],
           [0.5, -0.91, 0.26 ,-0.5],
           [-0.26, -0.27, 0.17, 0.87]]

biases = [2, 3, 0.5]


layer_outputs = []

for neuron_weights, neuron_bias in zip(weights, biases):
    neuron_output = 0
    for n_input, weight in zip(inputs, neuron_weights):
        neuron_output += n_input * weight
    neuron_output += neuron_bias

    layer_outputs.append(neuron_output)

print(layer_outputs)


layer_outputs = np.dot(weights, inputs) + biases

print(layer_outputs)

4.8
[4.8, 1.21, 2.385]
[4.8, 1.21, 2.385]
[4.8   1.21  2.385]


In [4]:
import numpy as np
print(np.random.randn(3, 5))

layer_outputs = np.dot(weights, inputs) + biases
print(layer_outputs)

[[-0.85601537 -0.62255878  0.90315973 -0.67443506 -0.68941503]
 [-1.46773908  0.87623847 -0.22587473 -0.67044155  0.15469463]
 [-0.77623827  2.31722878 -0.17821492 -0.41532267  2.77157742]]
[4.8   1.21  2.385]
